# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fe5593fdcbbecc8fb9e39e9c3043c553d7e824b7c4d8ee47eeb61ace5576e3df9da360559a41d063d324e23fbc162b33f2d4f764b93e9f9f7557886ff13be4e

test:
  secret_key_base: 4967411aff72c9804eb589f522823c1f0e5b5cccf093dfdaddc31134f3571cef084c001f3239bd3475df9ae4ed1694b567596691bf2ca98655e91c6e8a1675cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
